version: '3.7'
services:
  composer:
    build:
      context: ./docker/composer
    container_name: composer
    volumes: 
      - ./cakeStudyApp/cms:/app/cms:cached
    command: [tail, -f, /dev/null]
  php:
    build:
      context: ./docker/php
    volumes:
      - ./cakeStudyApp/cms:/app/cms:cached
    container_name: php
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - 80:80
    volumes:
      - ./cakeStudyApp/cms:/app/cms:cached
      - ./docker/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
  db:
    build:
      context: ./docker/db
    container_name: db
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
     